from __future__ import annotations

from src.twobody.backend_factory import get_density_backend, get_shot_backend
from src.twobody.actionability import summarize_actionability_surface
from src.twobody.decision import (
    DecisionModel,
    accuracy_score,
    balanced_accuracy_score,
    compute_classification_metrics,
    decision_predictions,
    decision_scores,
    fit_linear_classifier,
    fit_logistic_regression,
    fit_threshold_classifier,
    matthews_corrcoef,
    pr_auc_score,
    precision_recall_f1,
    roc_auc_score,
    summarize_decision_records,
)
from src.twobody.evolution import build_evolution_circuit, compose_state_and_evolution
from src.twobody.features import extract_features, summarize_feature_survival_records
from src.twobody.fingerprint import (
    CentroidFingerprintModel,
    fit_centroid_fingerprint_model,
    predict_fingerprint_node,
    summarize_fingerprint_classification,
    summarize_fingerprint_stability,
    summarize_tamper_detection,
)
from src.twobody.hamiltonian import build_pauli_hamiltonian, describe_hamiltonian
from src.twobody.latent import (
    estimate_bell_probe_latents,
    estimate_latent,
    evaluate_latent_calibration,
    summarize_identifiability_records,
)
from src.twobody.pipeline import (
    build_base_circuit,
    inject_noise,
    measure_expectations,
    run_feature_pipeline,
    run_latent_pipeline,
)
from src.twobody.regime_map import classify_regime, summarize_regime_map
from src.twobody.transition import (
    classify_transition_state,
    summarize_transition_records,
    summarize_transition_surface_records,
)
from src.twobody.noise import (
    add_amplitude_noise,
    add_dephasing_noise,
    add_depolarizing_noise,
    add_measurement_noise,
    apply_amplitude_damping_channel,
    apply_coherent_noise_block,
    apply_correlated_phase_drift,
    apply_dephasing_channel,
    apply_depolarizing_channel,
    apply_local_phase_drift,
    apply_stochastic_noise_block,
    build_amplitude_damping_error,
    build_dephasing_error,
    build_depolarizing_error,
    build_measurement_noise_model,
    build_noise_model,
    describe_noise_config,
)
from src.twobody.observables import (
    build_measurement_circuit_for_pauli,
    get_observable_specs,
    observable_to_pauli_op,
)
from src.twobody.paper_figures import classify_paper_regime, contiguous_region_spans
from src.twobody.qiskit_density import (
    estimate_expectations_from_density,
    get_density_matrix,
    run_density_experiment,
)
from src.twobody.qiskit_shot import (
    estimate_expectations_from_counts,
    estimate_pauli_expectation_from_counts,
    run_shot_experiment,
)
from src.twobody.reconstruction import (
    compensate_expectations,
    dephasing_attenuation,
    observable_mae,
    observable_mae_by_family,
    summarize_reconstruction_records,
    transverse_pauli_count,
)
from src.twobody.states import available_state_families, build_state_circuit
from src.twobody.types import (
    BackendConfig,
    DensityExperimentResult,
    NoiseConfig,
    ObservableSpec,
    SystemConfig,
)

__all__ = [
    "summarize_actionability_surface",
    "DecisionModel",
    "accuracy_score",
    "balanced_accuracy_score",
    "BackendConfig",
    "CentroidFingerprintModel",
    "DensityExperimentResult",
    "NoiseConfig",
    "ObservableSpec",
    "SystemConfig",
    "available_state_families",
    "build_evolution_circuit",
    "build_measurement_circuit_for_pauli",
    "build_measurement_noise_model",
    "build_noise_model",
    "build_pauli_hamiltonian",
    "build_state_circuit",
    "classify_paper_regime",
    "compensate_expectations",
    "contiguous_region_spans",
    "dephasing_attenuation",
    "describe_noise_config",
    "compose_state_and_evolution",
    "compute_classification_metrics",
    "decision_predictions",
    "decision_scores",
    "describe_hamiltonian",
    "estimate_bell_probe_latents",
    "estimate_latent",
    "evaluate_latent_calibration",
    "estimate_expectations_from_density",
    "estimate_expectations_from_counts",
    "estimate_pauli_expectation_from_counts",
    "extract_features",
    "fit_centroid_fingerprint_model",
    "fit_linear_classifier",
    "fit_logistic_regression",
    "fit_threshold_classifier",
    "get_density_backend",
    "get_density_matrix",
    "get_observable_specs",
    "get_shot_backend",
    "matthews_corrcoef",
    "observable_to_pauli_op",
    "observable_mae",
    "observable_mae_by_family",
    "pr_auc_score",
    "precision_recall_f1",
    "predict_fingerprint_node",
    "roc_auc_score",
    "run_density_experiment",
    "run_feature_pipeline",
    "run_latent_pipeline",
    "run_shot_experiment",
    "build_base_circuit",
    "inject_noise",
    "measure_expectations",
    "classify_regime",
    "classify_transition_state",
    "summarize_regime_map",
    "summarize_transition_records",
    "summarize_transition_surface_records",
    "summarize_decision_records",
    "summarize_fingerprint_classification",
    "summarize_fingerprint_stability",
    "summarize_identifiability_records",
    "summarize_feature_survival_records",
    "summarize_reconstruction_records",
    "summarize_tamper_detection",
    "transverse_pauli_count",
    "add_amplitude_noise",
    "add_dephasing_noise",
    "add_depolarizing_noise",
    "add_measurement_noise",
    "apply_amplitude_damping_channel",
    "apply_coherent_noise_block",
    "apply_correlated_phase_drift",
    "apply_dephasing_channel",
    "apply_depolarizing_channel",
    "apply_local_phase_drift",
    "apply_stochastic_noise_block",
    "build_amplitude_damping_error",
    "build_dephasing_error",
    "build_depolarizing_error",
]
